- name: Deploy Docker Compose App
  hosts: target_server
  become: true
  vars:
    project_path: "{{ workspace }}"  # Use the passed workspace path

  tasks:
    - name: Stop and remove existing containers
      shell: |
        docker-compose down
        docker rm -f mysql-db || true
      args:
        chdir: "{{ project_path }}"

    - name: Start MySQL
      shell: docker-compose up -d db
      args:
        chdir: "{{ project_path }}"

    - name: Wait for MySQL to start
      pause:
        seconds: 60

    - name: Start other services
      shell: docker-compose up -d
      args:
        chdir: "{{ project_path }}"
