- name: Deploy Docker Compose App Locally
  hosts: localhost
  connection: local  # Runs everything on WSL locally
  become: true  # Runs commands with sudo

  tasks:
    - name: Stop and remove existing containers
      shell: |
        docker-compose down
        docker rm -f mysql-db || true
      args:
        chdir: "{{ workspace }}"

    - name: Start MySQL
      shell: docker-compose up -d db
      args:
        chdir: "{{ workspace }}"

    - name: Wait for MySQL to start
      pause:
        seconds: 60

    - name: Start other services
      shell: docker-compose up -d
      args:
        chdir: "{{ workspace }}"
